### ISSUE TITLE
macOS go get error  -> undefined: unix.InotifyEvent

### ISSUE THREAD

**Issue by huhuegg** [tywkeene/go-fsevents#8]
go get github.com/tywkeene/go-fsevents
`# github.com/tywkeene/go-fsevents`
`../github.com/tywkeene/go-fsevents/fsevents.go:35:12: undefined: unix.InotifyEvent`

**Comment by tywkeene** [comment]
Inotify is a Linux kernel subsystem, and as such will not work on other kernels.

Sorry, there's really no way to fix this.

**Comment by mpkondrashin** [comment]
How to install this module on macOS to cross-compile for Linux?

**Comment by tywkeene** [comment]
I'm not sure what you mean by cross compile.

If you'd like to watch a directory on a mac, or develop with go-fsevents on a mac, you can use the docker desktop app for macs. Since docker desktop is actually a Linux VM under the hood, it has access to the correct libraries to build and run a program with go-fsevents. We have a few dockerfiles under the `docker/` directory in the repo that you can use as a jumping off point.

Other than that, it's literally down to whether the kernel is Linux or not, and Mac obviously isn't. If you're looking for something mac native that's similar to inotify, you might try one of the other packages named similarly.

**Comment by mpkondrashin** [comment]
I develop an application using go that is targeted for Linux and Windows. It requires recursive file system monitoring. So I need Go modules for monitoring the filesystem for both platforms. Using environment variable (i.e. GOOS=linux) I can use Go to build a project for Linux using my macOS. Same with Windows. I can get .EXE file using Go on my mac. I have found go-fsevents module suitable for Linux version of my application, but I can not install it on my mac. I assume that I will also not be able to install it on Windows. I do not want to use two separate platforms to develop one application.

**Comment by tywkeene** [comment]
So as I mentioned in my previous comment, even if you do get this to build using `GOOS=linux`, the program will not function on any machine that isn't running Linux. This isn't a limitation of the package itself, but rather the fact that the inotify subsystem is specifically a Linux kernel feature.

If you need to monitor filesystems on Mac/Windows, I've had success using Docker Desktop as I mentioned before, other than that, you may need to explore other, native options for each OS.

You might have some luck with this project instead: https://github.com/fsnotify/fsnotify

**Comment by mpkondrashin** [comment]
Hi! Thank you for your input!

I am perfectly Ok with not be able to run this application under
macOS/Windows. Cross-compilation will produce ELF file for Linux and it
will not run under macOS/Windows in any case.

Unfortunately, my application is not containerized by design. The customer
expects it to be a native Windows/Linux service

fsnotify is not recursive, so it does not fit my needs.


пн, 19 апр. 2021 г. в 20:54, Tyrell Keene ***@***.***>:
